name: "Test"

concurrency:
  group: ${{ github.workflow }} ${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

on:
  pull_request: {}
  push:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        kongVersion:
        - "3.6.1.4"

    steps:
    - uses: actions/checkout@v3

    - uses: Kong/kong-license@master
      # this step is only for Kong Inc internal uses, external users should
      # use the 'license' parameter of the kong-pongo action.
      with:
        op-token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

    - uses: Kong/kong-pongo-action@v1
      with:
        pongo_version: "2.10.0"
        kong_version: ${{ matrix.kongVersion }}

    - run: pongo run -- --Xoutput "--color" --coverage
